repos:
-  repo: https://github.com/hadialqattan/pycln
   rev: v2.2.2
   hooks:
   -  id: pycln
-  repo: https://github.com/PyCQA/isort
   rev: 5.12.0
   hooks:
   -  id: isort
-  repo: https://github.com/psf/black
   rev: 23.9.1
   hooks:
   -  id: black
